# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Doug Johnson's Homepage
email: dougj892@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site doesn't contain anything right now.  I might use it as a blogging platform later.  Or maybe not.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: dougj8921
github_username:  dougj892

# Build settings
markdown: kramdown
